language: python
sudo: false

matrix:
  include:
    - python: "2.7"
      env: DEPS="libgfortran=1.0 numpy=1.9 scipy=0.16 pandas=0.16 trackpy emcee"
    - python: "3.6"
      env: DEPS="numpy scipy pandas trackpy emcee"


install:
  - conda update --yes conda
  - conda config --append channels conda-forge
  - conda create -n testenv --yes $DEPS pip nose setuptools python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - python setup.py install

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script:
  - nosetests --nologcapture -a '!slow'
